title: C# dla początkujących
description: Kurs podstaw programowania konsolowego w C# dla uczniów i początkujących programistów
baseurl: "/csharp-basics-2026"
theme: jekyll-theme-slate
markdown: kramdown

defaults:
  - scope:
      path: ""
    values:
      layout: default


